export interface CountrySquareTrack {
  id: number
  title: string
  artist: string
  duration: string
  audioUrl: string
  downloadUrl: string
  coverArt?: string
}

export const countrySquareTracks: CountrySquareTrack[] = [
  {
    id: 1,
    title: "At The Old Town Diner",
    artist: "Country Square Artist",
    duration: "3:47",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/At%20The%20Old%20Town%20Diner-e4NMGM11XM1g8p7Sk17Be8H7VhUC5v.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/At%20The%20Old%20Town%20Diner-e4NMGM11XM1g8p7Sk17Be8H7VhUC5v.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 2,
    title: "Already Winning",
    artist: "Country Square Artist",
    duration: "4:03",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Already%20Winning-skMhAPXUEhJS1cl9dfStusPh1ngIbo.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Already%20Winning-skMhAPXUEhJS1cl9dfStusPh1ngIbo.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 3,
    title: "A Drive Out Of Town",
    artist: "Country Square Artist",
    duration: "3:55",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/A%20Drive%20Out%20Of%20Town-NBhRrdgR6Yeh0QQlUU9PRgLWffRxRV.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/A%20Drive%20Out%20Of%20Town-NBhRrdgR6Yeh0QQlUU9PRgLWffRxRV.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 4,
    title: "Blowing Smoke",
    artist: "Country Square Artist",
    duration: "3:38",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Blowing%20Smoke-MilHyFDBBZTmSIjn4zYZ6rIwQmmkfw.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Blowing%20Smoke-MilHyFDBBZTmSIjn4zYZ6rIwQmmkfw.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 5,
    title: "Beautiful Eyes",
    artist: "Country Square Artist",
    duration: "4:18",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Beautiful%20Eyes-O6c8Ijk733TyXZRb5bR8WPGEy3NSeh.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Beautiful%20Eyes-O6c8Ijk733TyXZRb5bR8WPGEy3NSeh.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 6,
    title: "Boots Dirty And Worn",
    artist: "Country Square Artist",
    duration: "3:51",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Boots%20Dirty%20And%20Worn-fugukCN6e8XURiby03mVpjJUocnWEk.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Boots%20Dirty%20And%20Worn-fugukCN6e8XURiby03mVpjJUocnWEk.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 7,
    title: "Breaking Hearts",
    artist: "Country Square Artist",
    duration: "4:07",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Breaking%20Hearts-iwEp9PPPBDu7EvpFlTiwzHb9MGUb5t.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Breaking%20Hearts-iwEp9PPPBDu7EvpFlTiwzHb9MGUb5t.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 8,
    title: "Could Have Been Here",
    artist: "Country Square Artist",
    duration: "3:44",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Could%20Have%20Been%20Here-V1XbxYbp6hE1HKajMI9dgrlLZFDoE5.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Could%20Have%20Been%20Here-V1XbxYbp6hE1HKajMI9dgrlLZFDoE5.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 9,
    title: "Come Get It",
    artist: "Country Square Artist",
    duration: "3:29",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Come%20Get%20it-dHRHnT09OlEs8taEuRwVWlFFMzVaV0.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Come%20Get%20it-dHRHnT09OlEs8taEuRwVWlFFMzVaV0.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 10,
    title: "Chaos In Designer Hills",
    artist: "Country Square Artist",
    duration: "4:14",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chaos%20In%20Designer%20Hills-wKitObPuNkiZmEZd8ORMPXt4oJGLpg.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chaos%20In%20Designer%20Hills-wKitObPuNkiZmEZd8ORMPXt4oJGLpg.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 11,
    title: "Girl From Choctaw",
    artist: "Country Square Artist",
    duration: "3:52",
    audioUrl: "/audio/girl-from-choctaw.mp3",
    downloadUrl: "/audio/girl-from-choctaw.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 12,
    title: "Even When I Am Drunk",
    artist: "Country Square Artist",
    duration: "4:15",
    audioUrl: "/audio/even-when-i-am-drunk.mp3",
    downloadUrl: "/audio/even-when-i-am-drunk.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 13,
    title: "Giggling Under The Tree",
    artist: "Country Square Artist",
    duration: "3:38",
    audioUrl: "/audio/giggling-under-the-tree.mp3",
    downloadUrl: "/audio/giggling-under-the-tree.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 14,
    title: "Do I Get A Name",
    artist: "Country Square Artist",
    duration: "4:02",
    audioUrl: "/audio/do-i-get-a-name.mp3",
    downloadUrl: "/audio/do-i-get-a-name.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 15,
    title: "Danger In A Sundress",
    artist: "Country Square Artist",
    duration: "3:44",
    audioUrl: "/audio/danger-in-a-sundress.mp3",
    downloadUrl: "/audio/danger-in-a-sundress.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 16,
    title: "Heartquake",
    artist: "Country Square Artist",
    duration: "4:11",
    audioUrl: "/audio/heartquake.mp3",
    downloadUrl: "/audio/heartquake.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 17,
    title: "Even When I Am Drunk II",
    artist: "Country Square Artist",
    duration: "4:08",
    audioUrl: "/audio/even-when-i-am-drunk-ii.mp3",
    downloadUrl: "/audio/even-when-i-am-drunk-ii.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 18,
    title: "Angel Wings and Devils Hunger",
    artist: "Country Square Artist",
    duration: "3:57",
    audioUrl: "/audio/angel-wings-and-devils-hunger.mp3",
    downloadUrl: "/audio/angel-wings-and-devils-hunger.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 19,
    title: "Engine's Still Running",
    artist: "Country Square Artist",
    duration: "4:23",
    audioUrl: "/audio/engines-still-running.mp3",
    downloadUrl: "/audio/engines-still-running.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 20,
    title: "Love In Kansas",
    artist: "Country Square Artist",
    duration: "3:48",
    audioUrl: "/audio/love-in-kansas-updated.mp3",
    downloadUrl: "/audio/love-in-kansas-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 21,
    title: "Let's Chase That Moon Down",
    artist: "Country Square Artist",
    duration: "4:12",
    audioUrl: "/audio/lets-chase-that-moon-down-updated.mp3",
    downloadUrl: "/audio/lets-chase-that-moon-down-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 22,
    title: "Never Stood A Chance",
    artist: "Country Square Artist",
    duration: "3:55",
    audioUrl: "/audio/never-stood-a-chance-updated.mp3",
    downloadUrl: "/audio/never-stood-a-chance-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 23,
    title: "Let's Make A Life",
    artist: "Country Square Artist",
    duration: "4:07",
    audioUrl: "/audio/lets-make-a-life-updated.mp3",
    downloadUrl: "/audio/lets-make-a-life-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 24,
    title: "Memories Of A Love Past",
    artist: "Country Square Artist",
    duration: "3:41",
    audioUrl: "/audio/memories-of-a-love-past-updated.mp3",
    downloadUrl: "/audio/memories-of-a-love-past-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 25,
    title: "I Am Here Now",
    artist: "Country Square Artist",
    duration: "4:19",
    audioUrl: "/audio/i-am-here-now-updated.mp3",
    downloadUrl: "/audio/i-am-here-now-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 26,
    title: "Love You Like I Do (Country)",
    artist: "Country Square Artist",
    duration: "3:53",
    audioUrl: "/audio/love-you-like-i-do-country-updated.mp3",
    downloadUrl: "/audio/love-you-like-i-do-country-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 27,
    title: "Memories Of A Love Past II",
    artist: "Country Square Artist",
    duration: "4:04",
    audioUrl: "/audio/memories-of-a-love-past-ii-updated.mp3",
    downloadUrl: "/audio/memories-of-a-love-past-ii-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 28,
    title: "I Like The Ride",
    artist: "Country Square Artist",
    duration: "3:37",
    audioUrl: "/audio/i-like-the-ride-updated.mp3",
    downloadUrl: "/audio/i-like-the-ride-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 29,
    title: "Missing Out",
    artist: "Country Square Artist",
    duration: "4:14",
    audioUrl: "/audio/missing-out-updated.mp3",
    downloadUrl: "/audio/missing-out-updated.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 30,
    title: "Skipping Rocks",
    artist: "Country Square Artist",
    duration: "3:46",
    audioUrl: "/audio/skipping-rocks.mp3",
    downloadUrl: "/audio/skipping-rocks.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 31,
    title: "Never Stood A Chance",
    artist: "Country Square Artist",
    duration: "4:01",
    audioUrl: "/audio/never-stood-a-chance-v2.mp3",
    downloadUrl: "/audio/never-stood-a-chance-v2.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 32,
    title: "Thanks Heavens She's Home",
    artist: "Country Square Artist",
    duration: "3:58",
    audioUrl: "/audio/thanks-heavens-shes-home.mp3",
    downloadUrl: "/audio/thanks-heavens-shes-home.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 33,
    title: "Playing For Keeps",
    artist: "Country Square Artist",
    duration: "4:13",
    audioUrl: "/audio/playing-for-keeps.mp3",
    downloadUrl: "/audio/playing-for-keeps.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 34,
    title: "New Places",
    artist: "Country Square Artist",
    duration: "3:42",
    audioUrl: "/audio/new-places.mp3",
    downloadUrl: "/audio/new-places.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 35,
    title: "Pull Up A Chair",
    artist: "Country Square Artist",
    duration: "4:09",
    audioUrl: "/audio/pull-up-a-chair.mp3",
    downloadUrl: "/audio/pull-up-a-chair.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 36,
    title: "No Such Thing As Too Hot",
    artist: "Country Square Artist",
    duration: "3:54",
    audioUrl: "/audio/no-such-thing-as-too-hot.mp3",
    downloadUrl: "/audio/no-such-thing-as-too-hot.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 37,
    title: "Red Wine And Roses",
    artist: "Country Square Artist",
    duration: "4:16",
    audioUrl: "/audio/red-wine-and-roses.mp3",
    downloadUrl: "/audio/red-wine-and-roses.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 38,
    title: "Sun Will Shine Again II",
    artist: "Country Square Artist",
    duration: "3:51",
    audioUrl: "/audio/sun-will-shine-again-ii.mp3",
    downloadUrl: "/audio/sun-will-shine-again-ii.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 39,
    title: "Storm In My Heart",
    artist: "Country Square Artist",
    duration: "4:05",
    audioUrl: "/audio/storm-in-my-heart.mp3",
    downloadUrl: "/audio/storm-in-my-heart.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 40,
    title: "Too Soon",
    artist: "Country Square Artist",
    duration: "3:43",
    audioUrl: "/audio/too-soon.mp3",
    downloadUrl: "/audio/too-soon.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 41,
    title: "Wicked Grin",
    artist: "Country Square Artist",
    duration: "4:02",
    audioUrl: "/audio/wicked-grin.mp3",
    downloadUrl: "/audio/wicked-grin.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 42,
    title: "This Well Is Dry",
    artist: "Country Square Artist",
    duration: "3:56",
    audioUrl: "/audio/this-well-is-dry.mp3",
    downloadUrl: "/audio/this-well-is-dry.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 43,
    title: "Whispering Things",
    artist: "Country Square Artist",
    duration: "4:08",
    audioUrl: "/audio/whispering-things.mp3",
    downloadUrl: "/audio/whispering-things.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 44,
    title: "Wild Idea",
    artist: "Country Square Artist",
    duration: "3:47",
    audioUrl: "/audio/wild-idea.mp3",
    downloadUrl: "/audio/wild-idea.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 45,
    title: "Too Hot",
    artist: "Country Square Artist",
    duration: "4:11",
    audioUrl: "/audio/too-hot.mp3",
    downloadUrl: "/audio/too-hot.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 46,
    title: "The Sun Will Shine Again",
    artist: "Country Square Artist",
    duration: "3:54",
    audioUrl: "/audio/the-sun-will-shine-again.mp3",
    downloadUrl: "/audio/the-sun-will-shine-again.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 47,
    title: "Velvet Rope",
    artist: "Country Square Artist",
    duration: "4:17",
    audioUrl: "/audio/velvet-rope.mp3",
    downloadUrl: "/audio/velvet-rope.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 48,
    title: "Wildfire",
    artist: "Country Square Artist",
    duration: "3:49",
    audioUrl: "/audio/wildfire-v2.mp3",
    downloadUrl: "/audio/wildfire-v2.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 49,
    title: "Unusual",
    artist: "Country Square Artist",
    duration: "4:06",
    audioUrl: "/audio/unusual.mp3",
    downloadUrl: "/audio/unusual.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 50,
    title: "Your Kiss Gives Me Life",
    artist: "Country Square Artist",
    duration: "3:58",
    audioUrl: "/audio/your-kiss-gives-me-life.mp3",
    downloadUrl: "/audio/your-kiss-gives-me-life.mp3",
    coverArt: "/country-square.jpg",
  },
  {
    id: 51,
    title: "You Move Earth",
    artist: "Country Square Artist",
    duration: "4:03",
    audioUrl: "/audio/you-move-earth.mp3",
    downloadUrl: "/audio/you-move-earth.mp3",
    coverArt: "/country-square.jpg",
  },
]

export function getAllCountrySquareTracks(): CountrySquareTrack[] {
  return countrySquareTracks
}

export function getCountrySquareTrackById(id: number): CountrySquareTrack | undefined {
  return countrySquareTracks.find((track) => track.id === id)
}
