export interface PopSquareTrack {
  id: number
  title: string
  artist: string
  duration: string
  audioUrl: string
  downloadUrl: string
  coverArt?: string
}

export const popSquareTracks: PopSquareTrack[] = [
  {
    id: 1,
    title: "Back It Up",
    artist: "Pop Square Artist",
    duration: "3:42",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Back%20It%20Up-jdTBUAxVvre65c2tnDpl6iCQlwDA6g.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Back%20It%20Up-jdTBUAxVvre65c2tnDpl6iCQlwDA6g.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 2,
    title: "Back It Up (Pop Cover)",
    artist: "Pop Square Artist",
    duration: "3:38",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Back%20it%20Up%28Pop%20Cover%29-5Gycdvgc5DjNgkhYUoUjoQ0RYtZUez.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Back%20it%20Up%28Pop%20Cover%29-5Gycdvgc5DjNgkhYUoUjoQ0RYtZUez.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 3,
    title: "Butterfly (R&B)",
    artist: "Pop Square Artist",
    duration: "4:15",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Butterfly%20R%26B-cL5LL7ah8C9cd8ljkiydxBbGvj922J.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Butterfly%20R%26B-cL5LL7ah8C9cd8ljkiydxBbGvj922J.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 4,
    title: "Beautiful Things (Pop)",
    artist: "Pop Square Artist",
    duration: "3:52",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Beautiful%20Things%20Pop-GekB1E9by2uqlXEoXDhb4IHWuO04u5.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Beautiful%20Things%20Pop-GekB1E9by2uqlXEoXDhb4IHWuO04u5.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 5,
    title: "Butterfly",
    artist: "Pop Square Artist",
    duration: "4:08",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Butterfly-fAYLgklhZwehVMzp9B4LnFul12i44u.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Butterfly-fAYLgklhZwehVMzp9B4LnFul12i44u.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 6,
    title: "Damn The Radio",
    artist: "Pop Square Artist",
    duration: "3:45",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Damn%20The%20Radio-EVrf5AJUyVNERMHpSo1zS2E0dOXW3J.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Damn%20The%20Radio-EVrf5AJUyVNERMHpSo1zS2E0dOXW3J.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 7,
    title: "Drink Or Dreams",
    artist: "Pop Square Artist",
    duration: "4:22",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Drink%20Or%20Dreams-5jw51kXctFhAQsQknNJBMDNrU09a5q.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Drink%20Or%20Dreams-5jw51kXctFhAQsQknNJBMDNrU09a5q.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 8,
    title: "Feel Real Good",
    artist: "Pop Square Artist",
    duration: "3:58",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Feel%20Real%20Good-2dPswGTGgVu4H6RIzpdw2p5vLQk10A.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Feel%20Real%20Good-2dPswGTGgVu4H6RIzpdw2p5vLQk10A.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 9,
    title: "Deep End",
    artist: "Pop Square Artist",
    duration: "4:03",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Deep%20End-KvZTTUqvHEaJD6I5z2bYnKBAF2Cr60.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Deep%20End-KvZTTUqvHEaJD6I5z2bYnKBAF2Cr60.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 10,
    title: "Dancing Tonight",
    artist: "Pop Square Artist",
    duration: "3:47",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Dancing%20Tonight-ax9IYNLSACnbCD1FX22Hp2IeQgQy4H.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Dancing%20Tonight-ax9IYNLSACnbCD1FX22Hp2IeQgQy4H.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 11,
    title: "I Got This",
    artist: "Pop Square Artist",
    duration: "3:45",
    audioUrl: "/audio/i-got-this.mp3",
    downloadUrl: "/audio/i-got-this.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 12,
    title: "I'll Take Right Now Too",
    artist: "Pop Square Artist",
    duration: "4:12",
    audioUrl: "/audio/ill-take-right-now-too.mp3",
    downloadUrl: "/audio/ill-take-right-now-too.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 13,
    title: "Floating",
    artist: "Pop Square Artist",
    duration: "3:58",
    audioUrl: "/audio/floating.mp3",
    downloadUrl: "/audio/floating.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 14,
    title: "Hit The Jackpot",
    artist: "Pop Square Artist",
    duration: "4:05",
    audioUrl: "/audio/hit-the-jackpot.mp3",
    downloadUrl: "/audio/hit-the-jackpot.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 15,
    title: "Heartbreak Songs And Long Drives",
    artist: "Pop Square Artist",
    duration: "4:28",
    audioUrl: "/audio/heartbreak-songs-and-long-drives.mp3",
    downloadUrl: "/audio/heartbreak-songs-and-long-drives.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 16,
    title: "Heartbreak Songs",
    artist: "Pop Square Artist",
    duration: "3:52",
    audioUrl: "/audio/heartbreak-songs.mp3",
    downloadUrl: "/audio/heartbreak-songs.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 17,
    title: "Get To The Loving",
    artist: "Pop Square Artist",
    duration: "4:15",
    audioUrl: "/audio/get-to-the-loving.mp3",
    downloadUrl: "/audio/get-to-the-loving.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 18,
    title: "Hearts In The Sand",
    artist: "Pop Square Artist",
    duration: "3:47",
    audioUrl: "/audio/hearts-in-the-sand.mp3",
    downloadUrl: "/audio/hearts-in-the-sand.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 19,
    title: "Heartbreak",
    artist: "Pop Square Artist",
    duration: "4:03",
    audioUrl: "/audio/heartbreak.mp3",
    downloadUrl: "/audio/heartbreak.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 20,
    title: "Fine Anyway",
    artist: "Pop Square Artist",
    duration: "3:39",
    audioUrl: "/audio/fine-anyway.mp3",
    downloadUrl: "/audio/fine-anyway.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 21,
    title: "It Is Fate",
    artist: "Pop Square Artist",
    duration: "3:54",
    audioUrl: "/audio/it-is-fate.mp3",
    downloadUrl: "/audio/it-is-fate.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 22,
    title: "More Than That",
    artist: "Pop Square Artist",
    duration: "4:08",
    audioUrl: "/audio/more-than-that.mp3",
    downloadUrl: "/audio/more-than-that.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 23,
    title: "Legendary",
    artist: "Pop Square Artist",
    duration: "3:42",
    audioUrl: "/audio/legendary.mp3",
    downloadUrl: "/audio/legendary.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 24,
    title: "More Than That II",
    artist: "Pop Square Artist",
    duration: "4:16",
    audioUrl: "/audio/more-than-that-ii.mp3",
    downloadUrl: "/audio/more-than-that-ii.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 25,
    title: "Never Looking Back",
    artist: "Pop Square Artist",
    duration: "3:51",
    audioUrl: "/audio/never-looking-back.mp3",
    downloadUrl: "/audio/never-looking-back.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 26,
    title: "Let's Talk about It",
    artist: "Pop Square Artist",
    duration: "4:02",
    audioUrl: "/audio/lets-talk-about-it.mp3",
    downloadUrl: "/audio/lets-talk-about-it.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 27,
    title: "No Guard Up",
    artist: "Pop Square Artist",
    duration: "3:37",
    audioUrl: "/audio/no-guard-up.mp3",
    downloadUrl: "/audio/no-guard-up.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 28,
    title: "Legendary II",
    artist: "Pop Square Artist",
    duration: "4:11",
    audioUrl: "/audio/legendary-ii.mp3",
    downloadUrl: "/audio/legendary-ii.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 29,
    title: "Let it Linger",
    artist: "Pop Square Artist",
    duration: "3:48",
    audioUrl: "/audio/let-it-linger.mp3",
    downloadUrl: "/audio/let-it-linger.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 30,
    title: "Never Could I Imagine",
    artist: "Pop Square Artist",
    duration: "4:25",
    audioUrl: "/audio/never-could-i-imagine.mp3",
    downloadUrl: "/audio/never-could-i-imagine.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 31,
    title: "Nobody's Fool",
    artist: "Pop Square Artist",
    duration: "3:56",
    audioUrl: "/audio/nobodys-fool.mp3",
    downloadUrl: "/audio/nobodys-fool.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 32,
    title: "Revolving Door",
    artist: "Pop Square Artist",
    duration: "4:13",
    audioUrl: "/audio/revolving-door.mp3",
    downloadUrl: "/audio/revolving-door.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 33,
    title: "Should Have Told Me",
    artist: "Pop Square Artist",
    duration: "3:41",
    audioUrl: "/audio/should-have-told-me.mp3",
    downloadUrl: "/audio/should-have-told-me.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 34,
    title: "Right Now",
    artist: "Pop Square Artist",
    duration: "4:07",
    audioUrl: "/audio/right-now.mp3",
    downloadUrl: "/audio/right-now.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 35,
    title: "Only Live Once",
    artist: "Pop Square Artist",
    duration: "3:53",
    audioUrl: "/audio/only-live-once.mp3",
    downloadUrl: "/audio/only-live-once.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 36,
    title: "Sexy & Dumb",
    artist: "Pop Square Artist",
    duration: "4:01",
    audioUrl: "/audio/sexy-and-dumb.mp3",
    downloadUrl: "/audio/sexy-and-dumb.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 37,
    title: "Over and Out",
    artist: "Pop Square Artist",
    duration: "3:44",
    audioUrl: "/audio/over-and-out.mp3",
    downloadUrl: "/audio/over-and-out.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 38,
    title: "Pure (Kinda)",
    artist: "Pop Square Artist",
    duration: "4:18",
    audioUrl: "/audio/pure-kinda.mp3",
    downloadUrl: "/audio/pure-kinda.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 39,
    title: "Oops...I Like Him",
    artist: "Pop Square Artist",
    duration: "3:35",
    audioUrl: "/audio/oops-i-like-him.mp3",
    downloadUrl: "/audio/oops-i-like-him.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 40,
    title: "Smooth Talker",
    artist: "Pop Square Artist",
    duration: "4:09",
    audioUrl: "/audio/smooth-talker.mp3",
    downloadUrl: "/audio/smooth-talker.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 41,
    title: "Too Soon To Know (Dance Mix)",
    artist: "Pop Square Artist",
    duration: "3:58",
    audioUrl: "/audio/too-soon-to-know-dance-mix.mp3",
    downloadUrl: "/audio/too-soon-to-know-dance-mix.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 42,
    title: "Take A Picture",
    artist: "Pop Square Artist",
    duration: "4:05",
    audioUrl: "/audio/take-a-picture.mp3",
    downloadUrl: "/audio/take-a-picture.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 43,
    title: "Watch Me Move",
    artist: "Pop Square Artist",
    duration: "3:47",
    audioUrl: "/audio/watch-me-move.mp3",
    downloadUrl: "/audio/watch-me-move.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 44,
    title: "Stars Align",
    artist: "Pop Square Artist",
    duration: "4:12",
    audioUrl: "/audio/stars-align.mp3",
    downloadUrl: "/audio/stars-align.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 45,
    title: "What Do I Do Now",
    artist: "Pop Square Artist",
    duration: "3:51",
    audioUrl: "/audio/what-do-i-do-now.mp3",
    downloadUrl: "/audio/what-do-i-do-now.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 46,
    title: "Thought You Knew",
    artist: "Pop Square Artist",
    duration: "4:03",
    audioUrl: "/audio/thought-you-knew.mp3",
    downloadUrl: "/audio/thought-you-knew.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 47,
    title: "The Mess I Like",
    artist: "Pop Square Artist",
    duration: "3:39",
    audioUrl: "/audio/the-mess-i-like.mp3",
    downloadUrl: "/audio/the-mess-i-like.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 48,
    title: "What's Going On (Big Band Cover)",
    artist: "Pop Square Artist",
    duration: "4:22",
    audioUrl: "/audio/whats-going-on-big-band-cover.mp3",
    downloadUrl: "/audio/whats-going-on-big-band-cover.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 49,
    title: "Tons II",
    artist: "Pop Square Artist",
    duration: "3:45",
    audioUrl: "/audio/tons-ii.mp3",
    downloadUrl: "/audio/tons-ii.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 50,
    title: "Too Late Babe",
    artist: "Pop Square Artist",
    duration: "4:08",
    audioUrl: "/audio/too-late-babe.mp3",
    downloadUrl: "/audio/too-late-babe.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 51,
    title: "Wine Mom Anthem",
    artist: "Saka",
    duration: "3:28",
    audioUrl: "/audio/wine-mom-anthem.mp3",
    downloadUrl: "/audio/wine-mom-anthem.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 52,
    title: "Therapy Breakthrough",
    artist: "Saka",
    duration: "3:45",
    audioUrl: "/audio/therapy-breakthrough.mp3",
    downloadUrl: "/audio/therapy-breakthrough.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 53,
    title: "Toxic But Make It Fashion",
    artist: "Saka",
    duration: "3:52",
    audioUrl: "/audio/toxic-but-make-it-fashion.mp3",
    downloadUrl: "/audio/toxic-but-make-it-fashion.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 54,
    title: "Butterfly",
    artist: "Saka",
    duration: "3:58",
    audioUrl: "/audio/butterfly.mp3",
    downloadUrl: "/audio/butterfly.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 55,
    title: "Mirror Talk",
    artist: "Saka",
    duration: "3:42",
    audioUrl: "/audio/mirror-talk-saka.mp3",
    downloadUrl: "/audio/mirror-talk-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 56,
    title: "Bad Texter",
    artist: "Saka",
    duration: "3:28",
    audioUrl: "/audio/bad-texter-saka.mp3",
    downloadUrl: "/audio/bad-texter-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 57,
    title: "Ex Files",
    artist: "Saka",
    duration: "4:05",
    audioUrl: "/audio/ex-files-saka.mp3",
    downloadUrl: "/audio/ex-files-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 58,
    title: "Girl Math",
    artist: "Saka",
    duration: "3:33",
    audioUrl: "/audio/girl-math-saka.mp3",
    downloadUrl: "/audio/girl-math-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 59,
    title: "Glow Up Season",
    artist: "Saka",
    duration: "3:51",
    audioUrl: "/audio/glow-up-season-saka.mp3",
    downloadUrl: "/audio/glow-up-season-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 60,
    title: "Designer Heartbreak",
    artist: "Saka",
    duration: "4:12",
    audioUrl: "/audio/designer-heartbreak-saka.mp3",
    downloadUrl: "/audio/designer-heartbreak-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 61,
    title: "Hot Girl Summer Internship",
    artist: "Saka",
    duration: "3:47",
    audioUrl: "/audio/hot-girl-summer-internship-saka.mp3",
    downloadUrl: "/audio/hot-girl-summer-internship-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 62,
    title: "Emotional Support Playlist",
    artist: "Saka",
    duration: "4:18",
    audioUrl: "/audio/emotional-support-playlist-saka.mp3",
    downloadUrl: "/audio/emotional-support-playlist-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 63,
    title: "Mommy Juice",
    artist: "Saka",
    duration: "3:39",
    audioUrl: "/audio/mommy-juice-saka.mp3",
    downloadUrl: "/audio/mommy-juice-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 64,
    title: "Red Flag Collector I",
    artist: "Saka",
    duration: "3:54",
    audioUrl: "/audio/red-flag-collector-i-saka.mp3",
    downloadUrl: "/audio/red-flag-collector-i-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 65,
    title: "Block Party",
    artist: "Saka",
    duration: "3:31",
    audioUrl: "/audio/block-party-saka.mp3",
    downloadUrl: "/audio/block-party-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 66,
    title: "Swiping Through My Feelings",
    artist: "Saka",
    duration: "4:02",
    audioUrl: "/audio/swiping-through-my-feelings-saka.mp3",
    downloadUrl: "/audio/swiping-through-my-feelings-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 67,
    title: "Therapy Breakthrough II",
    artist: "Saka",
    duration: "3:48",
    audioUrl: "/audio/therapy-breakthrough-ii-saka.mp3",
    downloadUrl: "/audio/therapy-breakthrough-ii-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 68,
    title: "Red Flag Collector",
    artist: "Saka",
    duration: "3:57",
    audioUrl: "/audio/red-flag-collector-saka.mp3",
    downloadUrl: "/audio/red-flag-collector-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 69,
    title: "Standards Rising",
    artist: "Saka",
    duration: "4:08",
    audioUrl: "/audio/standards-rising-saka.mp3",
    downloadUrl: "/audio/standards-rising-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 70,
    title: "Pillow Princess",
    artist: "Saka",
    duration: "3:44",
    audioUrl: "/audio/pillow-princess-saka.mp3",
    downloadUrl: "/audio/pillow-princess-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 71,
    title: "Pillow Princess II",
    artist: "Saka",
    duration: "3:52",
    audioUrl: "/audio/pillow-princess-ii-saka.mp3",
    downloadUrl: "/audio/pillow-princess-ii-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 72,
    title: "Self-Care Sunday",
    artist: "Saka",
    duration: "4:15",
    audioUrl: "/audio/self-care-sunday-saka.mp3",
    downloadUrl: "/audio/self-care-sunday-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
  {
    id: 73,
    title: "Queen of Overthinking",
    artist: "Saka",
    duration: "3:36",
    audioUrl: "/audio/queen-of-overthinking-saka.mp3",
    downloadUrl: "/audio/queen-of-overthinking-saka.mp3",
    coverArt: "/pop-square-vol1.jpg",
  },
]

export function getAllPopSquareTracks(): PopSquareTrack[] {
  return popSquareTracks
}

export function getPopSquareTrackById(id: number): PopSquareTrack | undefined {
  return popSquareTracks.find((track) => track.id === id)
}
