export interface RnBSquareTrack {
  id: number
  title: string
  artist: string
  duration: string
  audioUrl: string
  downloadUrl: string
  coverArt?: string
}

export const rnbSquareTracks: RnBSquareTrack[] = [
  {
    id: 1,
    title: "Can't Hide",
    artist: "R&B Square Artist",
    duration: "3:42",
    audioUrl: "/audio/cant-hide.mp3",
    downloadUrl: "/audio/cant-hide.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 2,
    title: "Breakfast In Bed",
    artist: "R&B Square Artist",
    duration: "4:15",
    audioUrl: "/audio/breakfast-in-bed.mp3",
    downloadUrl: "/audio/breakfast-in-bed.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 3,
    title: "A Night To Remember",
    artist: "R&B Square Artist",
    duration: "3:58",
    audioUrl: "/audio/a-night-to-remember.mp3",
    downloadUrl: "/audio/a-night-to-remember.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 4,
    title: "Around You",
    artist: "R&B Square Artist",
    duration: "4:03",
    audioUrl: "/audio/around-you.mp3",
    downloadUrl: "/audio/around-you.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 5,
    title: "Care For You",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl: "/audio/care-for-you.mp3",
    downloadUrl: "/audio/care-for-you.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 6,
    title: "Beautiful Things",
    artist: "R&B Square Artist",
    duration: "4:21",
    audioUrl: "/audio/beautiful-things.mp3",
    downloadUrl: "/audio/beautiful-things.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 7,
    title: "Care For You II",
    artist: "R&B Square Artist",
    duration: "3:54",
    audioUrl: "/audio/care-for-you-ii.mp3",
    downloadUrl: "/audio/care-for-you-ii.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 8,
    title: "Believer",
    artist: "R&B Square Artist",
    duration: "4:08",
    audioUrl: "/audio/believer.mp3",
    downloadUrl: "/audio/believer.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 9,
    title: "Broken Things",
    artist: "R&B Square Artist",
    duration: "3:36",
    audioUrl: "/audio/broken-things.mp3",
    downloadUrl: "/audio/broken-things.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 10,
    title: "Bedtime Stories",
    artist: "R&B Square Artist",
    duration: "4:12",
    audioUrl: "/audio/bedtime-stories.mp3",
    downloadUrl: "/audio/bedtime-stories.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 11,
    title: "Chills On My Body",
    artist: "R&B Square Artist",
    duration: "4:15",
    audioUrl: "/audio/chills-on-my-body-new.mp3",
    downloadUrl: "/audio/chills-on-my-body-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 12,
    title: "Dancing In The Dark",
    artist: "R&B Square Artist",
    duration: "3:54",
    audioUrl: "/audio/dancing-in-the-dark-new.mp3",
    downloadUrl: "/audio/dancing-in-the-dark-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 13,
    title: "Do It For Me",
    artist: "R&B Square Artist",
    duration: "3:42",
    audioUrl: "/audio/do-it-for-me-new.mp3",
    downloadUrl: "/audio/do-it-for-me-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 14,
    title: "Good Game",
    artist: "R&B Square Artist",
    duration: "3:36",
    audioUrl: "/audio/good-game-new.mp3",
    downloadUrl: "/audio/good-game-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 15,
    title: "Fire On My Heart",
    artist: "R&B Square Artist",
    duration: "4:12",
    audioUrl: "/audio/fire-on-my-heart-new.mp3",
    downloadUrl: "/audio/fire-on-my-heart-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 16,
    title: "Hot & Rainy II",
    artist: "R&B Square Artist",
    duration: "4:08",
    audioUrl: "/audio/hot-and-rainy-ii-new.mp3",
    downloadUrl: "/audio/hot-and-rainy-ii-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 17,
    title: "Care For You (New Version)",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl: "/audio/care-for-you-new.mp3",
    downloadUrl: "/audio/care-for-you-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 18,
    title: "Grown & Fine",
    artist: "R&B Square Artist",
    duration: "4:21",
    audioUrl: "/audio/grown-and-fine-new.mp3",
    downloadUrl: "/audio/grown-and-fine-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 19,
    title: "Hard To Love",
    artist: "R&B Square Artist",
    duration: "3:58",
    audioUrl: "/audio/hard-to-love-new.mp3",
    downloadUrl: "/audio/hard-to-love-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 20,
    title: "Here For It",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl: "/audio/here-for-it-new.mp3",
    downloadUrl: "/audio/here-for-it-new.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 21,
    title: "Love You Like I Do",
    artist: "R&B Square Artist",
    duration: "4:05",
    audioUrl: "/audio/love-you-like-i-do-rnb.mp3",
    downloadUrl: "/audio/love-you-like-i-do-rnb.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 22,
    title: "Love You Like I Do (Unplugged)",
    artist: "R&B Square Artist",
    duration: "3:52",
    audioUrl: "/audio/love-you-like-i-do-unplugged.mp3",
    downloadUrl: "/audio/love-you-like-i-do-unplugged.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 23,
    title: "Mess Up The Bed",
    artist: "R&B Square Artist",
    duration: "4:18",
    audioUrl: "/audio/mess-up-the-bed.mp3",
    downloadUrl: "/audio/mess-up-the-bed.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 24,
    title: "Night To Remember",
    artist: "R&B Square Artist",
    duration: "3:44",
    audioUrl: "/audio/night-to-remember-rnb.mp3",
    downloadUrl: "/audio/night-to-remember-rnb.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 25,
    title: "Let's Make It A Night",
    artist: "R&B Square Artist",
    duration: "4:09",
    audioUrl: "/audio/lets-make-it-a-night.mp3",
    downloadUrl: "/audio/lets-make-it-a-night.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 26,
    title: "Point Of It All",
    artist: "R&B Square Artist",
    duration: "3:56",
    audioUrl: "/audio/point-of-it-all.mp3",
    downloadUrl: "/audio/point-of-it-all.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 27,
    title: "I Never Stood A Chance",
    artist: "R&B Square Artist",
    duration: "4:14",
    audioUrl: "/audio/i-never-stood-a-chance.mp3",
    downloadUrl: "/audio/i-never-stood-a-chance.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 28,
    title: "Out Of My Dreams",
    artist: "R&B Square Artist",
    duration: "3:48",
    audioUrl: "/audio/out-of-my-dreams.mp3",
    downloadUrl: "/audio/out-of-my-dreams.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 29,
    title: "Hot & Rainy",
    artist: "R&B Square Artist",
    duration: "4:02",
    audioUrl: "/audio/hot-and-rainy-rnb.mp3",
    downloadUrl: "/audio/hot-and-rainy-rnb.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 30,
    title: "Letting It Fall II",
    artist: "R&B Square Artist",
    duration: "3:59",
    audioUrl: "/audio/letting-it-fall-ii.mp3",
    downloadUrl: "/audio/letting-it-fall-ii.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 31,
    title: "The One",
    artist: "R&B Square Artist",
    duration: "4:07",
    audioUrl: "/audio/the-one.mp3",
    downloadUrl: "/audio/the-one.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 32,
    title: "The Little Things II",
    artist: "R&B Square Artist",
    duration: "3:51",
    audioUrl: "/audio/the-little-things-ii.mp3",
    downloadUrl: "/audio/the-little-things-ii.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 33,
    title: "The Little Things",
    artist: "R&B Square Artist",
    duration: "4:03",
    audioUrl: "/audio/the-little-things.mp3",
    downloadUrl: "/audio/the-little-things.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 34,
    title: "Safe Space",
    artist: "R&B Square Artist",
    duration: "3:45",
    audioUrl: "/audio/safe-space.mp3",
    downloadUrl: "/audio/safe-space.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 35,
    title: "Secret Lover",
    artist: "R&B Square Artist",
    duration: "4:16",
    audioUrl: "/audio/secret-lover.mp3",
    downloadUrl: "/audio/secret-lover.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 36,
    title: "Time Well Spent",
    artist: "R&B Square Artist",
    duration: "3:58",
    audioUrl: "/audio/time-well-spent.mp3",
    downloadUrl: "/audio/time-well-spent.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 37,
    title: "She's A Vibe",
    artist: "R&B Square Artist",
    duration: "4:11",
    audioUrl: "/audio/shes-a-vibe.mp3",
    downloadUrl: "/audio/shes-a-vibe.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 38,
    title: "Tears In The Sun",
    artist: "R&B Square Artist",
    duration: "3:49",
    audioUrl: "/audio/tears-in-the-sun.mp3",
    downloadUrl: "/audio/tears-in-the-sun.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 39,
    title: "Ready To Jump",
    artist: "R&B Square Artist",
    duration: "4:04",
    audioUrl: "/audio/ready-to-jump.mp3",
    downloadUrl: "/audio/ready-to-jump.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 40,
    title: "Room In Your Heart",
    artist: "R&B Square Artist",
    duration: "3:56",
    audioUrl: "/audio/room-in-your-heart.mp3",
    downloadUrl: "/audio/room-in-your-heart.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 41,
    title: "Tons",
    artist: "R&B Square Artist",
    duration: "4:13",
    audioUrl: "/audio/tons.mp3",
    downloadUrl: "/audio/tons.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 42,
    title: "Wrapped",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl: "/audio/wrapped.mp3",
    downloadUrl: "/audio/wrapped.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 43,
    title: "Wheels Fall Off",
    artist: "R&B Square Artist",
    duration: "4:05",
    audioUrl: "/audio/wheels-fall-off.mp3",
    downloadUrl: "/audio/wheels-fall-off.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 44,
    title: "You Have Found Me II",
    artist: "R&B Square Artist",
    duration: "3:52",
    audioUrl: "/audio/you-have-found-me-ii.mp3",
    downloadUrl: "/audio/you-have-found-me-ii.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 45,
    title: "You Know Better",
    artist: "R&B Square Artist",
    duration: "4:08",
    audioUrl: "/audio/you-know-better.mp3",
    downloadUrl: "/audio/you-know-better.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 46,
    title: "Walls Down",
    artist: "R&B Square Artist",
    duration: "3:59",
    audioUrl: "/audio/walls-down-rnb.mp3",
    downloadUrl: "/audio/walls-down-rnb.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 47,
    title: "You Have Found Me",
    artist: "R&B Square Artist",
    duration: "4:01",
    audioUrl: "/audio/you-have-found-me.mp3",
    downloadUrl: "/audio/you-have-found-me.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 48,
    title: "Weak",
    artist: "R&B Square Artist",
    duration: "3:43",
    audioUrl: "/audio/weak.mp3",
    downloadUrl: "/audio/weak.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 49,
    title: "Worth It Anyway",
    artist: "R&B Square Artist",
    duration: "4:17",
    audioUrl: "/audio/worth-it-anyway.mp3",
    downloadUrl: "/audio/worth-it-anyway.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 50,
    title: "Turn Around",
    artist: "R&B Square Artist",
    duration: "3:54",
    audioUrl: "/audio/turn-around.mp3",
    downloadUrl: "/audio/turn-around.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 51,
    title: "Golden Hour Confessions",
    artist: "Luv Tonez",
    duration: "3:48",
    audioUrl: "/audio/golden-hour-confessions.mp3",
    downloadUrl: "/audio/golden-hour-confessions.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 52,
    title: "Electric Souls II",
    artist: "Luv Tonez",
    duration: "4:02",
    audioUrl: "/audio/electric-souls-ii.mp3",
    downloadUrl: "/audio/electric-souls-ii.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 53,
    title: "Electric Souls",
    artist: "Luv Tonez",
    duration: "3:55",
    audioUrl: "/audio/electric-souls.mp3",
    downloadUrl: "/audio/electric-souls.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 54,
    title: "3AM Conversations",
    artist: "Luv Tonez",
    duration: "4:18",
    audioUrl: "/audio/3am-conversations.mp3",
    downloadUrl: "/audio/3am-conversations.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 55,
    title: "City Lights & Late Nights",
    artist: "Luv Tonez",
    duration: "3:42",
    audioUrl: "/audio/city-lights-late-nights.mp3",
    downloadUrl: "/audio/city-lights-late-nights.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 56,
    title: "Digital Love Letters",
    artist: "Luv Tonez",
    duration: "4:05",
    audioUrl: "/audio/digital-love-letters.mp3",
    downloadUrl: "/audio/digital-love-letters.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 57,
    title: "Bamboo Sheets",
    artist: "Luv Tonez",
    duration: "3:38",
    audioUrl: "/audio/bamboo-sheets.mp3",
    downloadUrl: "/audio/bamboo-sheets.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 58,
    title: "Kaleidoscope Hearts (Remix)",
    artist: "Luv Tonez",
    duration: "4:12",
    audioUrl: "/audio/kaleidoscope-hearts-remix.mp3",
    downloadUrl: "/audio/kaleidoscope-hearts-remix.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 59,
    title: "Gravity",
    artist: "Luv Tonez",
    duration: "3:51",
    audioUrl: "/audio/gravity.mp3",
    downloadUrl: "/audio/gravity.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 60,
    title: "Honey Drip",
    artist: "Luv Tonez",
    duration: "4:08",
    audioUrl: "/audio/honey-drip.mp3",
    downloadUrl: "/audio/honey-drip.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 61,
    title: "Neon Heartbreak",
    artist: "Luv Tonez",
    duration: "3:54",
    audioUrl: "/audio/neon-heartbreak.mp3",
    downloadUrl: "/audio/neon-heartbreak.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 62,
    title: "Rose Gold Feelings",
    artist: "Luv Tonez",
    duration: "4:16",
    audioUrl: "/audio/rose-gold-feelings.mp3",
    downloadUrl: "/audio/rose-gold-feelings.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 63,
    title: "Kaleidoscope Hearts",
    artist: "Luv Tonez",
    duration: "3:47",
    audioUrl: "/audio/kaleidoscope-hearts.mp3",
    downloadUrl: "/audio/kaleidoscope-hearts.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 64,
    title: "Kaleidoscope Hearts (Dance Mix)",
    artist: "Luv Tonez",
    duration: "4:23",
    audioUrl: "/audio/kaleidoscope-hearts-dance-mix.mp3",
    downloadUrl: "/audio/kaleidoscope-hearts-dance-mix.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 65,
    title: "Silk Road",
    artist: "Luv Tonez",
    duration: "4:01",
    audioUrl: "/audio/silk-road.mp3",
    downloadUrl: "/audio/silk-road.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 66,
    title: "Stardust Serenade (Extended)",
    artist: "Luv Tonez",
    duration: "5:12",
    audioUrl: "/audio/stardust-serenade-extended.mp3",
    downloadUrl: "/audio/stardust-serenade-extended.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 67,
    title: "Purple Rain Therapy",
    artist: "Luv Tonez",
    duration: "4:35",
    audioUrl: "/audio/purple-rain-therapy.mp3",
    downloadUrl: "/audio/purple-rain-therapy.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 68,
    title: "Midnight Frequencie",
    artist: "Luv Tonez",
    duration: "3:58",
    audioUrl: "/audio/midnight-frequencie.mp3",
    downloadUrl: "/audio/midnight-frequencie.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 69,
    title: "Slow Motion",
    artist: "Luv Tonez",
    duration: "4:14",
    audioUrl: "/audio/slow-motion.mp3",
    downloadUrl: "/audio/slow-motion.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 70,
    title: "Midnight Frequencies2",
    artist: "Luv Tonez",
    duration: "4:02",
    audioUrl: "/audio/midnight-frequencies2.mp3",
    downloadUrl: "/audio/midnight-frequencies2.mp3",
    coverArt: "/rnb-square.jpg",
  },
]

export function getAllRnBSquareTracks(): RnBSquareTrack[] {
  return rnbSquareTracks
}

export function getRnBSquareTrackById(id: number): RnBSquareTrack | undefined {
  return rnbSquareTracks.find((track) => track.id === id)
}
